# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)



# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["DockerCourseAPI/DockerCourseAPI.csproj", "DockerCourseAPI/"]
RUN dotnet restore "./DockerCourseAPI/DockerCourseAPI.csproj"
COPY . .
WORKDIR "/src/DockerCourseAPI"


RUN dotnet build "./DockerCourseAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet publish "./DockerCourseAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish . 
ENTRYPOINT ["dotnet", "DockerCourseAPI.dll"]